language: go

go:
  - 1.14.7

env: GO111MODULE=on

branches:
  except:
    - slave

arch:
  - amd64

os:
  - linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install make ; fi

script:
  - make
  - make test


#before_deploy:
#      # Set up git user name and tag this commit
#      - git config --local user.name "cheenwe"
#      - git config --local user.email "cheenwe@gmail.com"
#      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
#      - git tag $TRAVIS_TAG
#
#deploy:
# provider: releases
# api_key: $GITHUB_OAUTH_TOKEN
# file_glob: true
# file: builds/*
# skip_cleanup: true
##  prerelease: true
# on:
#   repo: cheenwe/KeepMeGo
#   branch: master
#
#after_deploy:
# - make clean
